# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4cab31cca1a164040fb5c882f1180ccad1b3b3c58e97948a3ea1c899383ccbebd8f4703ae95ace8246139200a83c4085e4313f58a1c133f92ac458203fb6506

test:
  secret_key_base: 4b0bebba93b87500a3d20bee0355418c31b00dc618e7ba365dda30a6a45dc6791072af21f35bbe2f849a069e98c67e796fae2600ab16fa220b5789fcd864afe3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
